



# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-storage-claim
#   namespace: backstage
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi

#production
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
  namespace: backstage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2   # or gp3 depending on your cluster
  resources:
    requests:
      storage: 1Gi

