name: Backstage CI/CD

on:
  push:
    branches:
      - 'feature2'   # ðŸ”¥ Trigger on ALL branches

env:
  #IMAGE_NAME: backstage
  IMAGE_NAME: backstage-production

jobs:
   

  # -----------------------------
  # JOB 1 â€” Build & Push Image
  # -----------------------------

  
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ðŸ”¥ FORCE NODE 24
      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          check-latest: true
          cache: 'yarn'

      - name: Verify Node Version
        run: node -v

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential python3 make g++

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # - name: Build backend
      #   run: yarn build:backend
      - name: Build backend
        env:
          # Matching your exact YAML placeholders
          APP_BASE_URL_FRONTEND: http://ae9a3c2abec9e42c0abde4b73fa2bd42-451734798.us-east-1.elb.amazonaws.com
          APP_BASE_URL_BACKEND: http://ae9a3c2abec9e42c0abde4b73fa2bd42-451734798.us-east-1.elb.amazonaws.com
          APP_CONFIG_auth_environment: production
        run: yarn build:backend

      - name: Set image tag
        id: meta
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     
      - name: Build Docker image
        run: |
            USERNAME="${{ secrets.DOCKER_USERNAME }}"
            IMAGE_NAME="${{ env.IMAGE_NAME }}"
            TAG=5
            IMAGE="$USERNAME/$IMAGE_NAME:$TAG"
            echo "Building image: $IMAGE"
            docker build . -f packages/backend/Dockerfile -t "$IMAGE"
        
      - name: Push Docker image
        run: |
            USERNAME="${{ secrets.DOCKER_USERNAME }}"
            IMAGE_NAME="${{ env.IMAGE_NAME }}"
            TAG=5
            IMAGE="$USERNAME/$IMAGE_NAME:$TAG"
            docker push "$IMAGE"

  
  # -----------------------------
  # JOB 2 â€” Deploy to Kubernetes
  # -----------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Remove any existing kubeconfig
        run: rm -rf $HOME/.kube

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name secure-eks-cluster

      - name: Verify cluster access
        run: |
          kubectl config view
          kubectl get nodes
          
      - name: Create namespace if not exists
        run: |
           kubectl get namespace backstage || kubectl create namespace backstage

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/ -n backstage
        
      - name: Deploy new image
        run: |
          USERNAME="${{ secrets.DOCKER_USERNAME }}"
          IMAGE_NAME="${{ env.IMAGE_NAME }}"
          TAG=5
          IMAGE="$USERNAME/$IMAGE_NAME:$TAG"
          kubectl set image deployment/backstage \
          backstage=$IMAGE \
          -n backstage
      - name: Verify rollout
        run: |
          kubectl rollout status deployment/backstage -n backstage
